version: '3.8'

services:
  client:
    container_name: socks5_proxy_client
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "1080:1080"
  server:
    container_name: socks5_proxy_server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "1081:1081"